import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';

const NewsCard = ({ news, index = 0 }) => {
    const formatDate = (dateString) => {
        const date = new Date(dateString);
        return date.toLocaleDateString('es-ES', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
    };

    const getPrimaryImage = () => {
        if (news.images && news.images.length > 0) {
            return news.images[0].url;
        }
        return 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&h=600&fit=crop';
    };

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: index * 0.1 }}
            className="news-card group"
        >
            <Link to={`/news/${news.id}`} className="block">
                {/* Image */}
                <div className="relative h-64 overflow-hidden rounded-t-2xl">
                    <motion.img
                        src={getPrimaryImage()}
                        alt={news.title}
                        className="w-full h-full object-cover"
                        whileHover={{ scale: 1.1 }}
                        transition={{ duration: 0.4 }}
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-dark-950 via-dark-950/50 to-transparent" />

                    {/* Tags */}
                    {news.tags && news.tags.length > 0 && (
                        <div className="absolute top-4 left-4 flex flex-wrap gap-2">
                            {news.tags.slice(0, 2).map((tag, idx) => (
                                <span
                                    key={idx}
                                    className="px-3 py-1 text-xs font-semibold glass rounded-full"
                                >
                                    {tag}
                                </span>
                            ))}
                        </div>
                    )}

                    {/* Auto-generated badge */}
                    {news.autoGenerated && (
                        <div className="absolute top-4 right-4">
                            <span className="px-3 py-1 text-xs font-semibold bg-accent-600/80 backdrop-blur-sm rounded-full flex items-center gap-1">
                                <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                                    <path d="M13 7H7v6h6V7z" />
                                    <path fillRule="evenodd" d="M7 2a1 1 0 012 0v1h2V2a1 1 0 112 0v1h2a2 2 0 012 2v2h1a1 1 0 110 2h-1v2h1a1 1 0 110 2h-1v2a2 2 0 01-2 2h-2v1a1 1 0 11-2 0v-1H9v1a1 1 0 11-2 0v-1H5a2 2 0 01-2-2v-2H2a1 1 0 110-2h1V9H2a1 1 0 010-2h1V5a2 2 0 012-2h2V2zM5 5h10v10H5V5z" clipRule="evenodd" />
                                </svg>
                                AI
                            </span>
                        </div>
                    )}
                </div>

                {/* Content */}
                <div className="p-6">
                    {/* Date and author */}
                    <div className="flex items-center gap-2 text-sm text-dark-400 mb-3">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                        <span>{formatDate(news.publishedAt || news.createdAt)}</span>
                        {news.authorSource && (
                            <>
                                <span>•</span>
                                <span>{news.authorSource}</span>
                            </>
                        )}
                    </div>

                    {/* Title */}
                    <h3 className="text-xl font-bold mb-3 line-clamp-2 group-hover:text-primary-400 transition-colors">
                        {news.title}
                    </h3>

                    {/* Excerpt */}
                    <p className="text-dark-300 line-clamp-3 mb-4">
                        {news.excerpt}
                    </p>

                    {/* Read more */}
                    <div className="flex items-center text-primary-400 font-semibold group-hover:gap-2 transition-all">
                        <span>Leer más</span>
                        <svg className="w-5 h-5 transform group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                        </svg>
                    </div>
                </div>
            </Link>
        </motion.div>
    );
};

export default NewsCard;
