package com.newsportal.dto;

import com.newsportal.model.News;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.HashSet;
import java.util.Set;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class NewsRequest {

    @NotBlank(message = "Title is required")
    @Size(max = 500, message = "Title must not exceed 500 characters")
    private String title;

    @Size(max = 1000, message = "Excerpt must not exceed 1000 characters")
    private String excerpt;

    @NotBlank(message = "Body is required")
    private String body;

    private String bodyHtml;

    private String authorSource;

    private String urlSource;

    @Builder.Default
    private Set<String> tags = new HashSet<>();

    @Builder.Default
    private News.NewsStatus status = News.NewsStatus.DRAFT;

    @Builder.Default
    private Boolean autoGenerated = false;

    private String generatedByJobId;
}
