package com.newsportal.dto;

import com.newsportal.model.News;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class NewsResponse {

    private Long id;
    private String title;
    private String excerpt;
    private String body;
    private String bodyHtml;
    private String authorSource;
    private String urlSource;

    @Builder.Default
    private Set<String> tags = new HashSet<>();

    private News.NewsStatus status;
    private LocalDateTime publishedAt;
    private Boolean autoGenerated;
    private String generatedByJobId;

    @Builder.Default
    private List<MediaAssetResponse> images = new ArrayList<>();

    private Long commentCount;
    private String createdByUsername;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
