package com.newsportal.service;

import com.newsportal.dto.MediaAssetResponse;
import com.newsportal.dto.NewsRequest;
import com.newsportal.dto.NewsResponse;
import com.newsportal.model.News;
import com.newsportal.model.User;
import com.newsportal.repository.CommentRepository;
import com.newsportal.repository.NewsRepository;
import com.newsportal.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class NewsService {

    private final NewsRepository newsRepository;
    private final UserRepository userRepository;
    private final CommentRepository commentRepository;
    private final AuditLogService auditLogService;

    @Transactional(readOnly = true)
    public Page<NewsResponse> getAllPublishedNews(Pageable pageable) {
        return newsRepository.findByStatusAndPublishedAtBefore(
                News.NewsStatus.PUBLISHED,
                LocalDateTime.now(),
                pageable).map(this::convertToResponse);
    }

    @Transactional(readOnly = true)
    public Page<NewsResponse> searchNews(String keyword, Pageable pageable) {
        return newsRepository.searchByKeyword(News.NewsStatus.PUBLISHED, keyword, pageable)
                .map(this::convertToResponse);
    }

    @Transactional(readOnly = true)
    public Page<NewsResponse> getNewsByTags(List<String> tags, Pageable pageable) {
        return newsRepository.findByTagsIn(tags, News.NewsStatus.PUBLISHED, pageable)
                .map(this::convertToResponse);
    }

    @Transactional(readOnly = true)
    public NewsResponse getNewsById(Long id) {
        News news = newsRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("News not found with id: " + id));

        // Only allow viewing published news for non-authenticated users
        if (news.getStatus() != News.NewsStatus.PUBLISHED) {
            String username = SecurityContextHolder.getContext().getAuthentication().getName();
            if (username == null || username.equals("anonymousUser")) {
                throw new RuntimeException("News not found");
            }
        }

        return convertToResponse(news);
    }

    @Transactional
    public NewsResponse createNews(NewsRequest request) {
        String username = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));

        News news = News.builder()
                .title(request.getTitle())
                .excerpt(request.getExcerpt())
                .body(request.getBody())
                .bodyHtml(request.getBodyHtml())
                .authorSource(request.getAuthorSource())
                .urlSource(request.getUrlSource())
                .tags(request.getTags())
                .status(request.getStatus())
                .autoGenerated(request.getAutoGenerated())
                .generatedByJobId(request.getGeneratedByJobId())
                .createdBy(user)
                .build();

        news = newsRepository.save(news);

        auditLogService.logAction("News", news.getId(), "CREATE", user, "News created: " + news.getTitle());

        return convertToResponse(news);
    }

    @Transactional
    public NewsResponse updateNews(Long id, NewsRequest request) {
        News news = newsRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("News not found with id: " + id));

        String username = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));

        String originalContent = news.getBody();

        news.setTitle(request.getTitle());
        news.setExcerpt(request.getExcerpt());
        news.setBody(request.getBody());
        news.setBodyHtml(request.getBodyHtml());
        news.setAuthorSource(request.getAuthorSource());
        news.setUrlSource(request.getUrlSource());
        news.setTags(request.getTags());
        news.setStatus(request.getStatus());

        news = newsRepository.save(news);

        auditLogService.logContentChange("News", news.getId(), "UPDATE", user,
                originalContent, news.getBody(), null, null);

        return convertToResponse(news);
    }

    @Transactional
    public void deleteNews(Long id) {
        News news = newsRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("News not found with id: " + id));

        String username = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));

        newsRepository.delete(news);

        auditLogService.logAction("News", id, "DELETE", user, "News deleted: " + news.getTitle());
    }

    @Transactional
    public NewsResponse publishNews(Long id) {
        News news = newsRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("News not found with id: " + id));

        String username = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));

        news.publish();
        news = newsRepository.save(news);

        auditLogService.logAction("News", news.getId(), "PUBLISH", user, "News published: " + news.getTitle());

        return convertToResponse(news);
    }

    @Transactional
    public NewsResponse rejectNews(Long id) {
        News news = newsRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("News not found with id: " + id));

        String username = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));

        news.reject();
        news = newsRepository.save(news);

        auditLogService.logAction("News", news.getId(), "REJECT", user, "News rejected: " + news.getTitle());

        return convertToResponse(news);
    }

    @Transactional(readOnly = true)
    public Page<NewsResponse> getAutoGeneratedNews(Pageable pageable) {
        return newsRepository.findByAutoGeneratedTrueAndStatus(News.NewsStatus.DRAFT, pageable)
                .map(this::convertToResponse);
    }

    private NewsResponse convertToResponse(News news) {
        Long commentCount = commentRepository.countByNewsIdAndApprovedTrue(news.getId());

        List<MediaAssetResponse> images = news.getImages().stream()
                .map(media -> MediaAssetResponse.builder()
                        .id(media.getId())
                        .url(media.getUrl())
                        .type(media.getType())
                        .fileSize(media.getFileSize())
                        .mimeType(media.getMimeType())
                        .width(media.getWidth())
                        .height(media.getHeight())
                        .altText(media.getAltText())
                        .generationPrompt(media.getGenerationPrompt())
                        .aiGenerated(media.getAiGenerated())
                        .displayOrder(media.getDisplayOrder())
                        .createdAt(media.getCreatedAt())
                        .build())
                .collect(Collectors.toList());

        return NewsResponse.builder()
                .id(news.getId())
                .title(news.getTitle())
                .excerpt(news.getExcerpt())
                .body(news.getBody())
                .bodyHtml(news.getBodyHtml())
                .authorSource(news.getAuthorSource())
                .urlSource(news.getUrlSource())
                .tags(news.getTags())
                .status(news.getStatus())
                .publishedAt(news.getPublishedAt())
                .autoGenerated(news.getAutoGenerated())
                .generatedByJobId(news.getGeneratedByJobId())
                .images(images)
                .commentCount(commentCount)
                .createdByUsername(news.getCreatedBy() != null ? news.getCreatedBy().getUsername() : null)
                .createdAt(news.getCreatedAt())
                .updatedAt(news.getUpdatedAt())
                .build();
    }
}
