package com.newsportal.repository;

import com.newsportal.model.News;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface NewsRepository extends JpaRepository<News, Long> {

    Page<News> findByStatus(News.NewsStatus status, Pageable pageable);

    Page<News> findByStatusAndPublishedAtBefore(News.NewsStatus status, LocalDateTime publishedAt, Pageable pageable);

    Page<News> findByAutoGeneratedTrue(Pageable pageable);

    Page<News> findByAutoGeneratedTrueAndStatus(News.NewsStatus status, Pageable pageable);

    @Query("SELECT n FROM News n WHERE n.status = :status AND " +
            "(LOWER(n.title) LIKE LOWER(CONCAT('%', :keyword, '%')) OR " +
            "LOWER(n.body) LIKE LOWER(CONCAT('%', :keyword, '%')))")
    Page<News> searchByKeyword(@Param("status") News.NewsStatus status,
            @Param("keyword") String keyword,
            Pageable pageable);

    @Query("SELECT n FROM News n JOIN n.tags t WHERE t IN :tags AND n.status = :status")
    Page<News> findByTagsIn(@Param("tags") List<String> tags,
            @Param("status") News.NewsStatus status,
            Pageable pageable);

    Optional<News> findByIdAndStatus(Long id, News.NewsStatus status);

    long countByStatus(News.NewsStatus status);

    long countByAutoGeneratedTrueAndStatus(News.NewsStatus status);
}
