import { useState } from 'react';
import { motion } from 'framer-motion';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { backofficeAPI } from '../lib/api';
import { Link } from 'react-router-dom';

const Backoffice = () => {
    const queryClient = useQueryClient();
    const [selectedNews, setSelectedNews] = useState(null);

    const { data: autoGeneratedNews, isLoading, error } = useQuery({
        queryKey: ['backoffice-news'],
        queryFn: () => backofficeAPI.getAutoGenerated().then(res => res.data),
    });

    const approveMutation = useMutation({
        mutationFn: backofficeAPI.approve,
        onSuccess: () => {
            queryClient.invalidateQueries(['backoffice-news']);
            setSelectedNews(null);
        },
    });

    const rejectMutation = useMutation({
        mutationFn: backofficeAPI.reject,
        onSuccess: () => {
            queryClient.invalidateQueries(['backoffice-news']);
            setSelectedNews(null);
        },
    });

    const handleApprove = (id) => {
        if (window.confirm('¿Estás seguro de aprobar esta noticia? Se publicará inmediatamente.')) {
            approveMutation.mutate(id);
        }
    };

    const handleReject = (id) => {
        if (window.confirm('¿Estás seguro de rechazar esta noticia? Se eliminará permanentemente.')) {
            rejectMutation.mutate(id);
        }
    };

    if (isLoading) {
        return (
            <div className="min-h-screen pt-24 pb-16">
                <div className="container mx-auto px-4">
                    <div className="shimmer h-12 w-64 rounded-lg mb-8" />
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {[...Array(6)].map((_, i) => (
                            <div key={i} className="shimmer h-64 rounded-2xl" />
                        ))}
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen pt-24 pb-16">
            <div className="container mx-auto px-4">
                <div className="flex items-center justify-between mb-8">
                    <h1 className="text-3xl font-display font-bold gradient-text">
                        Panel de Moderación
                    </h1>
                    <div className="flex gap-4">
                        <div className="px-4 py-2 glass rounded-xl text-sm">
                            Pendientes: <span className="font-bold text-primary-400">{autoGeneratedNews?.length || 0}</span>
                        </div>
                    </div>
                </div>

                {error ? (
                    <div className="card border-red-500/20 bg-red-500/5 text-center py-12">
                        <p className="text-red-400 text-lg mb-4">Error al cargar las noticias</p>
                        <p className="text-dark-400 text-sm">Verifica que tienes permisos de administrador</p>
                    </div>
                ) : autoGeneratedNews?.length === 0 ? (
                    <div className="card text-center py-16">
                        <div className="text-6xl mb-4">🎉</div>
                        <h2 className="text-2xl font-bold mb-2">¡Todo al día!</h2>
                        <p className="text-dark-300">No hay noticias pendientes de moderación.</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                        {/* List */}
                        <div className="space-y-4">
                            {autoGeneratedNews?.map((news) => (
                                <motion.div
                                    key={news.id}
                                    layoutId={`news-${news.id}`}
                                    onClick={() => setSelectedNews(news)}
                                    className={`card cursor-pointer transition-all ${selectedNews?.id === news.id
                                            ? 'border-primary-500 bg-white/10'
                                            : 'hover:bg-white/5'
                                        }`}
                                >
                                    <div className="flex gap-4">
                                        <div className="w-24 h-24 rounded-lg overflow-hidden flex-shrink-0 bg-dark-900">
                                            {news.images?.[0] ? (
                                                <img
                                                    src={news.images[0].url}
                                                    alt=""
                                                    className="w-full h-full object-cover"
                                                />
                                            ) : (
                                                <div className="w-full h-full flex items-center justify-center text-dark-500">
                                                    No img
                                                </div>
                                            )}
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <h3 className="font-bold text-lg mb-1 truncate">
                                                {news.title}
                                            </h3>
                                            <p className="text-sm text-dark-400 line-clamp-2 mb-2">
                                                {news.excerpt}
                                            </p>
                                            <div className="flex items-center gap-2 text-xs">
                                                <span className="px-2 py-1 glass rounded-full">
                                                    {news.authorSource || 'AI Generated'}
                                                </span>
                                                <span className="text-dark-500">
                                                    {new Date(news.createdAt).toLocaleDateString()}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </motion.div>
                            ))}
                        </div>

                        {/* Preview Panel */}
                        <div className="lg:sticky lg:top-24 h-fit">
                            {selectedNews ? (
                                <motion.div
                                    initial={{ opacity: 0, x: 20 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    key={selectedNews.id}
                                    className="card glass-strong"
                                >
                                    <div className="relative h-48 rounded-xl overflow-hidden mb-6">
                                        {selectedNews.images?.[0] && (
                                            <img
                                                src={selectedNews.images[0].url}
                                                alt=""
                                                className="w-full h-full object-cover"
                                            />
                                        )}
                                        <div className="absolute inset-0 bg-gradient-to-t from-dark-950/80 to-transparent" />
                                        <h2 className="absolute bottom-4 left-4 right-4 text-xl font-bold text-white">
                                            {selectedNews.title}
                                        </h2>
                                    </div>

                                    <div className="prose prose-invert prose-sm max-w-none mb-8 max-h-[400px] overflow-y-auto custom-scrollbar pr-2">
                                        <div dangerouslySetInnerHTML={{ __html: selectedNews.bodyHtml || selectedNews.body }} />
                                    </div>

                                    <div className="flex gap-4 pt-4 border-t border-white/10">
                                        <button
                                            onClick={() => handleApprove(selectedNews.id)}
                                            disabled={approveMutation.isPending}
                                            className="btn-primary flex-1 flex items-center justify-center gap-2"
                                        >
                                            {approveMutation.isPending ? 'Procesando...' : '✅ Aprobar y Publicar'}
                                        </button>
                                        <button
                                            onClick={() => handleReject(selectedNews.id)}
                                            disabled={rejectMutation.isPending}
                                            className="btn glass hover:bg-red-500/20 hover:border-red-500/50 text-red-400 flex-1"
                                        >
                                            {rejectMutation.isPending ? 'Procesando...' : '❌ Rechazar'}
                                        </button>
                                    </div>

                                    <div className="mt-4 text-center">
                                        <Link
                                            to={`/news/${selectedNews.id}`}
                                            className="text-sm text-primary-400 hover:underline"
                                            target="_blank"
                                        >
                                            Ver vista previa completa ↗
                                        </Link>
                                    </div>
                                </motion.div>
                            ) : (
                                <div className="card glass border-dashed border-2 border-white/10 flex items-center justify-center h-96 text-dark-400">
                                    <p>Selecciona una noticia para moderar</p>
                                </div>
                            )}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default Backoffice;
