import { motion } from 'framer-motion';
import { useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { newsAPI, commentsAPI } from '../lib/api';
import { useState } from 'react';

const NewsDetail = () => {
    const { id } = useParams();
    const queryClient = useQueryClient();
    const [commentText, setCommentText] = useState('');

    const { data: news, isLoading, error } = useQuery({
        queryKey: ['news', id],
        queryFn: () => newsAPI.getById(id).then(res => res.data),
    });

    const { data: comments } = useQuery({
        queryKey: ['comments', id],
        queryFn: () => commentsAPI.getByNewsId(id).then(res => res.data),
    });

    const createCommentMutation = useMutation({
        mutationFn: (text) => commentsAPI.create(id, { text }),
        onSuccess: () => {
            queryClient.invalidateQueries(['comments', id]);
            setCommentText('');
        },
    });

    const handleSubmitComment = (e) => {
        e.preventDefault();
        if (commentText.trim()) {
            createCommentMutation.mutate(commentText);
        }
    };

    const formatDate = (dateString) => {
        const date = new Date(dateString);
        return date.toLocaleDateString('es-ES', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    };

    const getPrimaryImage = () => {
        if (news?.images && news.images.length > 0) {
            return news.images[0].url;
        }
        return 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&h=800&fit=crop';
    };

    if (isLoading) {
        return (
            <div className="min-h-screen pt-24 pb-16">
                <div className="container mx-auto px-4 max-w-4xl">
                    <div className="shimmer h-96 rounded-2xl mb-8" />
                    <div className="shimmer h-12 rounded-lg mb-4" />
                    <div className="shimmer h-64 rounded-lg" />
                </div>
            </div>
        );
    }

    if (error || !news) {
        return (
            <div className="min-h-screen pt-24 pb-16">
                <div className="container mx-auto px-4 max-w-4xl">
                    <div className="card text-center py-12">
                        <p className="text-red-400 text-lg">Noticia no encontrada</p>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen pt-24 pb-16">
            <div className="container mx-auto px-4 max-w-4xl">
                {/* Hero Image */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="relative h-96 rounded-2xl overflow-hidden mb-8"
                >
                    <img
                        src={getPrimaryImage()}
                        alt={news.title}
                        className="w-full h-full object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-dark-950 via-dark-950/50 to-transparent" />

                    {/* Tags */}
                    {news.tags && news.tags.length > 0 && (
                        <div className="absolute top-6 left-6 flex flex-wrap gap-2">
                            {news.tags.map((tag, idx) => (
                                <span
                                    key={idx}
                                    className="px-4 py-2 text-sm font-semibold glass rounded-full"
                                >
                                    {tag}
                                </span>
                            ))}
                        </div>
                    )}

                    {news.autoGenerated && (
                        <div className="absolute top-6 right-6">
                            <span className="px-4 py-2 text-sm font-semibold bg-accent-600/80 backdrop-blur-sm rounded-full flex items-center gap-2">
                                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                                    <path d="M13 7H7v6h6V7z" />
                                    <path fillRule="evenodd" d="M7 2a1 1 0 012 0v1h2V2a1 1 0 112 0v1h2a2 2 0 012 2v2h1a1 1 0 110 2h-1v2h1a1 1 0 110 2h-1v2a2 2 0 01-2 2h-2v1a1 1 0 11-2 0v-1H9v1a1 1 0 11-2 0v-1H5a2 2 0 01-2-2v-2H2a1 1 0 110-2h1V9H2a1 1 0 010-2h1V5a2 2 0 012-2h2V2zM5 5h10v10H5V5z" clipRule="evenodd" />
                                </svg>
                                Generado con IA
                            </span>
                        </div>
                    )}
                </motion.div>

                {/* Article Content */}
                <motion.article
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    className="card mb-8"
                >
                    {/* Meta */}
                    <div className="flex items-center gap-4 text-sm text-dark-400 mb-6 pb-6 border-b border-white/10">
                        <div className="flex items-center gap-2">
                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                            </svg>
                            <span>{formatDate(news.publishedAt || news.createdAt)}</span>
                        </div>
                        {news.authorSource && (
                            <>
                                <span>•</span>
                                <div className="flex items-center gap-2">
                                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                                    </svg>
                                    <span>{news.authorSource}</span>
                                </div>
                            </>
                        )}
                    </div>

                    {/* Title */}
                    <h1 className="text-4xl md:text-5xl font-display font-bold mb-6">
                        {news.title}
                    </h1>

                    {/* Excerpt */}
                    {news.excerpt && (
                        <p className="text-xl text-dark-300 mb-8 pb-8 border-b border-white/10">
                            {news.excerpt}
                        </p>
                    )}

                    {/* Body */}
                    <div
                        className="prose prose-invert prose-lg max-w-none"
                        dangerouslySetInnerHTML={{ __html: news.bodyHtml || news.body }}
                    />

                    {/* Source */}
                    {news.urlSource && (
                        <div className="mt-8 pt-8 border-t border-white/10">
                            <p className="text-sm text-dark-400">
                                Fuente original:{' '}
                                <a
                                    href={news.urlSource}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-primary-400 hover:text-primary-300 underline"
                                >
                                    {news.urlSource}
                                </a>
                            </p>
                        </div>
                    )}
                </motion.article>

                {/* Comments Section */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.4 }}
                    className="card"
                >
                    <h2 className="text-2xl font-display font-bold mb-6 flex items-center gap-3">
                        <svg className="w-6 h-6 text-primary-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                        </svg>
                        Comentarios ({comments?.length || 0})
                    </h2>

                    {/* Comment Form */}
                    <form onSubmit={handleSubmitComment} className="mb-8">
                        <textarea
                            value={commentText}
                            onChange={(e) => setCommentText(e.target.value)}
                            placeholder="Escribe tu comentario..."
                            className="input min-h-[120px] resize-none mb-4"
                            rows={4}
                        />
                        <button
                            type="submit"
                            disabled={!commentText.trim() || createCommentMutation.isPending}
                            className="btn-primary"
                        >
                            {createCommentMutation.isPending ? 'Enviando...' : 'Publicar Comentario'}
                        </button>
                    </form>

                    {/* Comments List */}
                    <div className="space-y-4">
                        {comments?.map((comment) => (
                            <div key={comment.id} className="glass p-4 rounded-xl">
                                <div className="flex items-start gap-3">
                                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary-500 to-accent-500 flex items-center justify-center flex-shrink-0">
                                        <span className="text-white font-bold">
                                            {comment.user?.username?.[0]?.toUpperCase() || 'U'}
                                        </span>
                                    </div>
                                    <div className="flex-1">
                                        <div className="flex items-center gap-2 mb-2">
                                            <span className="font-semibold">{comment.user?.username || 'Usuario'}</span>
                                            <span className="text-sm text-dark-400">
                                                {formatDate(comment.createdAt)}
                                            </span>
                                        </div>
                                        <p className="text-dark-200">{comment.text}</p>
                                    </div>
                                </div>
                            </div>
                        ))}

                        {(!comments || comments.length === 0) && (
                            <p className="text-center text-dark-400 py-8">
                                No hay comentarios aún. ¡Sé el primero en comentar!
                            </p>
                        )}
                    </div>
                </motion.div>
            </div>
        </div>
    );
};

export default NewsDetail;
