package com.newsportal.api;

import com.newsportal.dto.CommentResponse;
import com.newsportal.dto.NewsResponse;
import com.newsportal.service.CommentService;
import com.newsportal.service.NewsService;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/backoffice")
@RequiredArgsConstructor
@CrossOrigin(origins = "*", maxAge = 3600)
@PreAuthorize("hasAnyRole('EDITOR', 'ADMIN', 'MODERATOR')")
public class BackofficeController {

    private final NewsService newsService;
    private final CommentService commentService;

    @GetMapping("/pending")
    public ResponseEntity<Page<NewsResponse>> getPendingNews(
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {

        Pageable pageable = PageRequest.of(page, size, Sort.by("createdAt").descending());
        Page<NewsResponse> news = newsService.getAutoGeneratedNews(pageable);
        return ResponseEntity.ok(news);
    }

    @PostMapping("/news/{id}/approve")
    public ResponseEntity<NewsResponse> approveNews(@PathVariable Long id) {
        NewsResponse news = newsService.publishNews(id);
        return ResponseEntity.ok(news);
    }

    @PostMapping("/news/{id}/reject")
    public ResponseEntity<NewsResponse> rejectNews(@PathVariable Long id) {
        NewsResponse news = newsService.rejectNews(id);
        return ResponseEntity.ok(news);
    }

    @GetMapping("/comments/unmoderated")
    public ResponseEntity<Page<CommentResponse>> getUnmoderatedComments(
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {

        Pageable pageable = PageRequest.of(page, size);
        Page<CommentResponse> comments = commentService.getUnmoderatedComments(pageable);
        return ResponseEntity.ok(comments);
    }

    @PostMapping("/comments/{id}/approve")
    public ResponseEntity<CommentResponse> approveComment(@PathVariable Long id) {
        CommentResponse comment = commentService.approveComment(id);
        return ResponseEntity.ok(comment);
    }

    @PostMapping("/comments/{id}/reject")
    public ResponseEntity<CommentResponse> rejectComment(@PathVariable Long id) {
        CommentResponse comment = commentService.rejectComment(id);
        return ResponseEntity.ok(comment);
    }
}
