package com.newsportal.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "news")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class News {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 500)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String excerpt;

    @Column(columnDefinition = "TEXT", nullable = false)
    private String body;

    @Column(name = "body_html", columnDefinition = "TEXT")
    private String bodyHtml;

    @Column(name = "author_source")
    private String authorSource;

    @Column(name = "url_source", length = 1000)
    private String urlSource;

    @ElementCollection
    @CollectionTable(name = "news_tags", joinColumns = @JoinColumn(name = "news_id"))
    @Column(name = "tag")
    @Builder.Default
    private Set<String> tags = new HashSet<>();

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private NewsStatus status = NewsStatus.DRAFT;

    @Column(name = "published_at")
    private LocalDateTime publishedAt;

    @Column(name = "auto_generated", nullable = false)
    @Builder.Default
    private Boolean autoGenerated = false;

    @Column(name = "generated_by_job_id")
    private String generatedByJobId;

    @OneToMany(mappedBy = "news", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<MediaAsset> images = new ArrayList<>();

    @OneToMany(mappedBy = "news", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<Comment> comments = new ArrayList<>();

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by_user_id")
    private User createdBy;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Helper methods
    public void addImage(MediaAsset image) {
        images.add(image);
        image.setNews(this);
    }

    public void removeImage(MediaAsset image) {
        images.remove(image);
        image.setNews(null);
    }

    public void addComment(Comment comment) {
        comments.add(comment);
        comment.setNews(this);
    }

    public void publish() {
        this.status = NewsStatus.PUBLISHED;
        this.publishedAt = LocalDateTime.now();
    }

    public void reject() {
        this.status = NewsStatus.REJECTED;
    }

    public String getPrimaryImageUrl() {
        return images.isEmpty() ? null : images.get(0).getUrl();
    }

    public void setPrimaryImageUrl(String url) {
        if (images.isEmpty()) {
            MediaAsset asset = new MediaAsset();
            asset.setUrl(url);
            asset.setType(MediaAsset.MediaType.IMAGE);
            addImage(asset);
        } else {
            images.get(0).setUrl(url);
        }
    }

    public void setTagsFromList(List<String> tagList) {
        if (tagList != null && !tagList.isEmpty()) {
            this.tags = new HashSet<>(tagList);
        }
    }

    public enum NewsStatus {
        DRAFT,
        PUBLISHED,
        REJECTED,
        ARCHIVED
    }
}
