import axios from 'axios';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080/api';

const api = axios.create({
    baseURL: API_BASE_URL,
    headers: {
        'Content-Type': 'application/json',
    },
});

// Request interceptor to add auth token
api.interceptors.request.use(
    (config) => {
        const token = localStorage.getItem('token');
        if (token) {
            config.headers.Authorization = `Bearer ${token}`;
        }
        return config;
    },
    (error) => {
        return Promise.reject(error);
    }
);

// Response interceptor to handle errors
api.interceptors.response.use(
    (response) => response,
    (error) => {
        if (error.response?.status === 401) {
            localStorage.removeItem('token');
            window.location.href = '/login';
        }
        return Promise.reject(error);
    }
);

// Auth API
export const authAPI = {
    login: (credentials) => api.post('/auth/login', credentials),
    register: (userData) => api.post('/auth/register', userData),
    getCurrentUser: () => api.get('/auth/me'),
};

// News API
export const newsAPI = {
    getAll: (params) => api.get('/news', { params }),
    getById: (id) => api.get(`/news/${id}`),
    create: (newsData) => api.post('/news', newsData),
    update: (id, newsData) => api.put(`/news/${id}`, newsData),
    delete: (id) => api.delete(`/news/${id}`),
    publish: (id) => api.post(`/news/${id}/publish`),
};

// Comments API
export const commentsAPI = {
    getByNewsId: (newsId) => api.get(`/news/${newsId}/comments`),
    create: (newsId, commentData) => api.post(`/news/${newsId}/comments`, commentData),
    delete: (newsId, commentId) => api.delete(`/news/${newsId}/comments/${commentId}`),
};

// Backoffice API
export const backofficeAPI = {
    getAutoGenerated: () => api.get('/backoffice/auto-generated'),
    approve: (id) => api.post(`/backoffice/news/${id}/approve`),
    reject: (id) => api.post(`/backoffice/news/${id}/reject`),
};

export default api;
